// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: models.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpendNote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address       string         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Commitment    []byte         `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	KeyIndex      uint32         `protobuf:"varint,3,opt,name=key_index,json=keyIndex,proto3" json:"key_index,omitempty"`
	ScriptHash    []byte         `protobuf:"bytes,4,opt,name=scriptHash,proto3" json:"scriptHash,omitempty"`
	Amount        uint64         `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset_ID      []byte         `protobuf:"bytes,6,opt,name=asset_ID,json=assetID,proto3" json:"asset_ID,omitempty"`
	State         []byte         `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Salt          []byte         `protobuf:"bytes,8,opt,name=salt,proto3" json:"salt,omitempty"`
	AccIndex      uint64         `protobuf:"varint,9,opt,name=acc_index,json=accIndex,proto3" json:"acc_index,omitempty"`
	WatchOnly     bool           `protobuf:"varint,10,opt,name=watch_only,json=watchOnly,proto3" json:"watch_only,omitempty"`
	Staked        bool           `protobuf:"varint,11,opt,name=staked,proto3" json:"staked,omitempty"`
	LockedUntil   int64          `protobuf:"varint,12,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	LockingScript *LockingScript `protobuf:"bytes,13,opt,name=locking_script,json=lockingScript,proto3" json:"locking_script,omitempty"`
}

func (x *SpendNote) Reset() {
	*x = SpendNote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendNote) ProtoMessage() {}

func (x *SpendNote) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendNote.ProtoReflect.Descriptor instead.
func (*SpendNote) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

func (x *SpendNote) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SpendNote) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *SpendNote) GetKeyIndex() uint32 {
	if x != nil {
		return x.KeyIndex
	}
	return 0
}

func (x *SpendNote) GetScriptHash() []byte {
	if x != nil {
		return x.ScriptHash
	}
	return nil
}

func (x *SpendNote) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SpendNote) GetAsset_ID() []byte {
	if x != nil {
		return x.Asset_ID
	}
	return nil
}

func (x *SpendNote) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SpendNote) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *SpendNote) GetAccIndex() uint64 {
	if x != nil {
		return x.AccIndex
	}
	return 0
}

func (x *SpendNote) GetWatchOnly() bool {
	if x != nil {
		return x.WatchOnly
	}
	return false
}

func (x *SpendNote) GetStaked() bool {
	if x != nil {
		return x.Staked
	}
	return false
}

func (x *SpendNote) GetLockedUntil() int64 {
	if x != nil {
		return x.LockedUntil
	}
	return 0
}

func (x *SpendNote) GetLockingScript() *LockingScript {
	if x != nil {
		return x.LockingScript
	}
	return nil
}

type WalletTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid    []byte                  `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	AmtIn   uint64                  `protobuf:"varint,2,opt,name=amtIn,proto3" json:"amtIn,omitempty"`
	AmtOut  uint64                  `protobuf:"varint,3,opt,name=amtOut,proto3" json:"amtOut,omitempty"`
	Inputs  []*WalletTransaction_IO `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs []*WalletTransaction_IO `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *WalletTransaction) Reset() {
	*x = WalletTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransaction) ProtoMessage() {}

func (x *WalletTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransaction.ProtoReflect.Descriptor instead.
func (*WalletTransaction) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

func (x *WalletTransaction) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *WalletTransaction) GetAmtIn() uint64 {
	if x != nil {
		return x.AmtIn
	}
	return 0
}

func (x *WalletTransaction) GetAmtOut() uint64 {
	if x != nil {
		return x.AmtOut
	}
	return 0
}

func (x *WalletTransaction) GetInputs() []*WalletTransaction_IO {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *WalletTransaction) GetOutputs() []*WalletTransaction_IO {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type AddrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr          string         `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	LockingScript *LockingScript `protobuf:"bytes,2,opt,name=locking_script,json=lockingScript,proto3" json:"locking_script,omitempty"`
	ScriptHash    []byte         `protobuf:"bytes,3,opt,name=script_hash,json=scriptHash,proto3" json:"script_hash,omitempty"`
	ViewPrivKey   []byte         `protobuf:"bytes,4,opt,name=view_priv_key,json=viewPrivKey,proto3" json:"view_priv_key,omitempty"`
	KeyIndex      uint32         `protobuf:"varint,5,opt,name=key_index,json=keyIndex,proto3" json:"key_index,omitempty"`
	WatchOnly     bool           `protobuf:"varint,6,opt,name=watch_only,json=watchOnly,proto3" json:"watch_only,omitempty"`
}

func (x *AddrInfo) Reset() {
	*x = AddrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfo) ProtoMessage() {}

func (x *AddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfo.ProtoReflect.Descriptor instead.
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{2}
}

func (x *AddrInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AddrInfo) GetLockingScript() *LockingScript {
	if x != nil {
		return x.LockingScript
	}
	return nil
}

func (x *AddrInfo) GetScriptHash() []byte {
	if x != nil {
		return x.ScriptHash
	}
	return nil
}

func (x *AddrInfo) GetViewPrivKey() []byte {
	if x != nil {
		return x.ViewPrivKey
	}
	return nil
}

func (x *AddrInfo) GetKeyIndex() uint32 {
	if x != nil {
		return x.KeyIndex
	}
	return 0
}

func (x *AddrInfo) GetWatchOnly() bool {
	if x != nil {
		return x.WatchOnly
	}
	return false
}

type LockingScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScriptCommitment []byte   `protobuf:"bytes,1,opt,name=script_commitment,json=scriptCommitment,proto3" json:"script_commitment,omitempty"`
	LockingParams    [][]byte `protobuf:"bytes,2,rep,name=locking_params,json=lockingParams,proto3" json:"locking_params,omitempty"`
}

func (x *LockingScript) Reset() {
	*x = LockingScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockingScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockingScript) ProtoMessage() {}

func (x *LockingScript) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockingScript.ProtoReflect.Descriptor instead.
func (*LockingScript) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{3}
}

func (x *LockingScript) GetScriptCommitment() []byte {
	if x != nil {
		return x.ScriptCommitment
	}
	return nil
}

func (x *LockingScript) GetLockingParams() [][]byte {
	if x != nil {
		return x.LockingParams
	}
	return nil
}

type WalletTransaction_IO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to IoType:
	//
	//	*WalletTransaction_IO_TxIo
	//	*WalletTransaction_IO_Unknown_
	IoType isWalletTransaction_IO_IoType `protobuf_oneof:"io_type"`
}

func (x *WalletTransaction_IO) Reset() {
	*x = WalletTransaction_IO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletTransaction_IO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransaction_IO) ProtoMessage() {}

func (x *WalletTransaction_IO) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransaction_IO.ProtoReflect.Descriptor instead.
func (*WalletTransaction_IO) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1, 0}
}

func (m *WalletTransaction_IO) GetIoType() isWalletTransaction_IO_IoType {
	if m != nil {
		return m.IoType
	}
	return nil
}

func (x *WalletTransaction_IO) GetTxIo() *WalletTransaction_IO_TxIO {
	if x, ok := x.GetIoType().(*WalletTransaction_IO_TxIo); ok {
		return x.TxIo
	}
	return nil
}

func (x *WalletTransaction_IO) GetUnknown() *WalletTransaction_IO_Unknown {
	if x, ok := x.GetIoType().(*WalletTransaction_IO_Unknown_); ok {
		return x.Unknown
	}
	return nil
}

type isWalletTransaction_IO_IoType interface {
	isWalletTransaction_IO_IoType()
}

type WalletTransaction_IO_TxIo struct {
	TxIo *WalletTransaction_IO_TxIO `protobuf:"bytes,1,opt,name=tx_io,json=txIo,proto3,oneof"`
}

type WalletTransaction_IO_Unknown_ struct {
	Unknown *WalletTransaction_IO_Unknown `protobuf:"bytes,2,opt,name=unknown,proto3,oneof"`
}

func (*WalletTransaction_IO_TxIo) isWalletTransaction_IO_IoType() {}

func (*WalletTransaction_IO_Unknown_) isWalletTransaction_IO_IoType() {}

type WalletTransaction_IO_TxIO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *WalletTransaction_IO_TxIO) Reset() {
	*x = WalletTransaction_IO_TxIO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletTransaction_IO_TxIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransaction_IO_TxIO) ProtoMessage() {}

func (x *WalletTransaction_IO_TxIO) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransaction_IO_TxIO.ProtoReflect.Descriptor instead.
func (*WalletTransaction_IO_TxIO) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *WalletTransaction_IO_TxIO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletTransaction_IO_TxIO) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WalletTransaction_IO_Unknown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WalletTransaction_IO_Unknown) Reset() {
	*x = WalletTransaction_IO_Unknown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletTransaction_IO_Unknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransaction_IO_Unknown) ProtoMessage() {}

func (x *WalletTransaction_IO_Unknown) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransaction_IO_Unknown.ProtoReflect.Descriptor instead.
func (*WalletTransaction_IO_Unknown) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1, 0, 1}
}

var File_models_proto protoreflect.FileDescriptor

var file_models_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d,
	0x03, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x5f, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x61, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x61, 0x63, 0x63, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a,
	0x0a, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x6b, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x6b, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x75,
	0x6e, 0x74, 0x69, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x35, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52,
	0x0d, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0xfa,
	0x02, 0x0a, 0x11, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6d, 0x74, 0x49,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x6d, 0x74, 0x49, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x74, 0x4f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x61, 0x6d, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x4f, 0x52, 0x06, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x4f, 0x52, 0x07, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x1a, 0xc2, 0x01, 0x0a, 0x02, 0x49, 0x4f, 0x12, 0x31, 0x0a,
	0x05, 0x74, 0x78, 0x5f, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x49, 0x4f, 0x2e, 0x54, 0x78, 0x49, 0x4f, 0x48, 0x00, 0x52, 0x04, 0x74, 0x78, 0x49, 0x6f,
	0x12, 0x39, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x4f, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x48, 0x00, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x1a, 0x38, 0x0a, 0x04, 0x54,
	0x78, 0x49, 0x4f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x09, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x42, 0x09, 0x0a, 0x07, 0x69, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x35, 0x0a, 0x0e,
	0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x0d, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x72, 0x69,
	0x76, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x76, 0x69, 0x65,
	0x77, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6b, 0x65, 0x79,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6f,
	0x6e, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x63, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x10, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_proto_rawDescOnce sync.Once
	file_models_proto_rawDescData = file_models_proto_rawDesc
)

func file_models_proto_rawDescGZIP() []byte {
	file_models_proto_rawDescOnce.Do(func() {
		file_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_proto_rawDescData)
	})
	return file_models_proto_rawDescData
}

var file_models_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_proto_goTypes = []interface{}{
	(*SpendNote)(nil),                    // 0: SpendNote
	(*WalletTransaction)(nil),            // 1: WalletTransaction
	(*AddrInfo)(nil),                     // 2: AddrInfo
	(*LockingScript)(nil),                // 3: LockingScript
	(*WalletTransaction_IO)(nil),         // 4: WalletTransaction.IO
	(*WalletTransaction_IO_TxIO)(nil),    // 5: WalletTransaction.IO.TxIO
	(*WalletTransaction_IO_Unknown)(nil), // 6: WalletTransaction.IO.Unknown
}
var file_models_proto_depIdxs = []int32{
	3, // 0: SpendNote.locking_script:type_name -> LockingScript
	4, // 1: WalletTransaction.inputs:type_name -> WalletTransaction.IO
	4, // 2: WalletTransaction.outputs:type_name -> WalletTransaction.IO
	3, // 3: AddrInfo.locking_script:type_name -> LockingScript
	5, // 4: WalletTransaction.IO.tx_io:type_name -> WalletTransaction.IO.TxIO
	6, // 5: WalletTransaction.IO.unknown:type_name -> WalletTransaction.IO.Unknown
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_models_proto_init() }
func file_models_proto_init() {
	if File_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendNote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockingScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletTransaction_IO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletTransaction_IO_TxIO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletTransaction_IO_Unknown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_models_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*WalletTransaction_IO_TxIo)(nil),
		(*WalletTransaction_IO_Unknown_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_proto_goTypes,
		DependencyIndexes: file_models_proto_depIdxs,
		MessageInfos:      file_models_proto_msgTypes,
	}.Build()
	File_models_proto = out.File
	file_models_proto_rawDesc = nil
	file_models_proto_goTypes = nil
	file_models_proto_depIdxs = nil
}
